backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
local_backend: true
locale: "pt"
media_folder: public/images
public_folder: images

collections:  
  - name: "livros"
    label: "Livros"      
    folder: "public/posts/livros"
    identifier_field: "nome"
    slug: "{{slug}}"
    extension: "json"
    create: true
    editor:
      preview: false
    fields:
      - { label: "nome", name: "nome", widget: "string"}
      - { label: "pdf", name: "link", widget: "file", media_folder: "files"}
      - { label: "capa", name: "src", widget: "image", media_folder: "images"}
  
  - name: "artigos"
    label: "Artigos"      
    folder: "public/posts/artigos"
    identifier_field: "nome"
    slug: "artigo-{{ano}}-{{slug}}"
    extension: "json"
    create: true
    editor:
      preview: false
    fields:
      - { label: "nome", name: "nome", widget: "string"}      
      - { label: "publicador", name: "publicador", widget: "string"}
      - { label: "versao", name: "versao", widget: "string"}
      - { label: "paginas", name: "paginas", widget: "string"}
      - { label: "ano", name: "ano", widget: "string"}
      - { label: "link", name: "link", widget: "string"}
      - { label: "autores", name: "autores", widget: "list"}
  - name: "patentes"
    label: "Patentes"      
    folder: "public/posts/patentes"
    identifier_field: "nome"
    slug: "patente-{{slug}}"
    extension: "json"
    create: true
    editor:
      preview: false
    fields:
      - { label: "nome", name: "nome", widget: "string"}      
      - { label: "link", name: "link", widget: "string"}
